INSERT INTO product (name, sport, category, price, description, size, color)
VALUES 
('Baseball', 'baseball', 'equipment', 1, 'Single baseball. Great for playing catch.', null, null),
('Baseball Bat', 'baseball', 'equipment', 15, 'Wooden bat for that old school feel.', null, 'Black'),
('Baseball Bat', 'baseball', 'equipment', 15, 'Wooden bat for that old school feel.', null, 'Red'),
('Baseball Bat', 'baseball', 'equipment', 15, 'Wooden bat for that old school feel.', null, 'Blue'),
('Baseball Glove', 'baseball', 'equipment', 20, 'Great glove for catching baseballs.', 'L', 'Black'),
('Baseball Glove', 'baseball', 'equipment', 20, 'Great glove for catching baseballs.', 'L', 'Pink'),
('Baseball Glove', 'baseball', 'equipment', 20, 'Great glove for catching baseballs.', 'L', 'Blue'),
('Baseball Glove', 'baseball', 'equipment', 20, 'Great glove for catching baseballs.', 'S', 'Black'),
('Baseball Glove', 'baseball', 'equipment', 20, 'Great glove for catching baseballs.', 'S', 'Pink'),
('Baseball Glove', 'baseball', 'equipment', 20, 'Great glove for catching baseballs.', 'S', 'Blue'),
('Baseball Tee', 'baseball', 'equipment', 15, 'Tee to set the baseball on and watch the kid swing', null, null),
('Catchers Mit', 'baseball', 'equipment', 20, 'Baseball mitt made for the catcher position', 'L', null),
('Catchers Mit', 'baseball', 'equipment', 20, 'Baseball mitt made for the catcher position', 'S', null),
('Catchers Gear', 'baseball', 'equipment', 20, 'Gear to protect the catcher at homeplate', 'S', null),
('Catchers Gear', 'baseball', 'equipment', 20, 'Gear to protect the catcher at homeplate', 'L', null),
('Baseball Hat', 'baseball', 'apparel', 10, 'Great looking and well made baseball hat.', 'L', 'Red'),
('Baseball Hat', 'baseball', 'apparel', 10, 'Great looking and well made baseball hat.', 'L', 'Blue'),
('Baseball Hat', 'baseball', 'apparel', 10, 'Great looking and well made baseball hat.', 'L', 'Black'),
('Baseball Hat', 'baseball', 'apparel', 10, 'Great looking and well made baseball hat.', 'L', 'White'),
('Baseball Hat', 'baseball', 'apparel', 10, 'Great looking and well made baseball hat.', 'L', 'Pink'),
('Baseball Hat', 'baseball', 'apparel', 10, 'Great looking and well made baseball hat.', 'M', 'Red'),
('Baseball Hat', 'baseball', 'apparel', 10, 'Great looking and well made baseball hat.', 'M', 'Blue'),
('Baseball Hat', 'baseball', 'apparel', 10, 'Great looking and well made baseball hat.', 'M', 'Black'),
('Baseball Hat', 'baseball', 'apparel', 10, 'Great looking and well made baseball hat.', 'M', 'White'),
('Baseball Hat', 'baseball', 'apparel', 10, 'Great looking and well made baseball hat.', 'M', 'Pink'),
('Baseball Hat', 'baseball', 'apparel', 10, 'Great looking and well made baseball hat.', 'S', 'Red'),
('Baseball Hat', 'baseball', 'apparel', 10, 'Great looking and well made baseball hat.', 'S', 'Blue'),
('Baseball Hat', 'baseball', 'apparel', 10, 'Great looking and well made baseball hat.', 'S', 'Black'),
('Baseball Hat', 'baseball', 'apparel', 10, 'Great looking and well made baseball hat.', 'S', 'White'),
('Baseball Hat', 'baseball', 'apparel', 10, 'Great looking and well made baseball hat.', 'S', 'Pink'),
('Baseball Jersey', 'baseball', 'apparel', 40, 'Great looking and well made baseball jersey.', 'L', 'Red'),
('Baseball Jersey', 'baseball', 'apparel', 40, 'Great looking and well made baseball jersey.', 'L', 'Blue'),
('Baseball Jersey', 'baseball', 'apparel', 40, 'Great looking and well made baseball jersey.', 'L', 'Black'),
('Baseball Jersey', 'baseball', 'apparel', 40, 'Great looking and well made baseball jersey.', 'L', 'White'),
('Baseball Jersey', 'baseball', 'apparel', 40, 'Great looking and well made baseball jersey.', 'L', 'Pink'),
('Baseball Jersey', 'baseball', 'apparel', 40, 'Great looking and well made baseball jersey.', 'M', 'Red'),
('Baseball Jersey', 'baseball', 'apparel', 40, 'Great looking and well made baseball jersey.', 'M', 'Blue'),
('Baseball Jersey', 'baseball', 'apparel', 40, 'Great looking and well made baseball jersey.', 'M', 'Black'),
('Baseball Jersey', 'baseball', 'apparel', 40, 'Great looking and well made baseball jersey.', 'M', 'White'),
('Baseball Jersey', 'baseball', 'apparel', 40, 'Great looking and well made baseball jersey.', 'M', 'Pink'),
('Baseball Jersey', 'baseball', 'apparel', 40, 'Great looking and well made baseball jersey.', 'S', 'Red'),
('Baseball Jersey', 'baseball', 'apparel', 40, 'Great looking and well made baseball jersey.', 'S', 'Blue'),
('Baseball Jersey', 'baseball', 'apparel', 40, 'Great looking and well made baseball jersey.', 'S', 'Black'),
('Baseball Jersey', 'baseball', 'apparel', 40, 'Great looking and well made baseball jersey.', 'S', 'White'),
('Baseball Jersey', 'baseball', 'apparel', 40, 'Great looking and well made baseball jersey.', 'S', 'Pink'),
('Baseball Pants', 'baseball', 'apparel', 20, 'Great looking and well made baseball pants.', 'L', 'Red'),
('Baseball Pants', 'baseball', 'apparel', 20, 'Great looking and well made baseball pants.', 'L', 'Blue'),
('Baseball Pants', 'baseball', 'apparel', 20, 'Great looking and well made baseball pants.', 'L', 'Black'),
('Baseball Pants', 'baseball', 'apparel', 20, 'Great looking and well made baseball pants.', 'L', 'White'),
('Baseball Pants', 'baseball', 'apparel', 20, 'Great looking and well made baseball pants.', 'L', 'Pink'),
('Baseball Pants', 'baseball', 'apparel', 20, 'Great looking and well made baseball pants.', 'M', 'Red'),
('Baseball Pants', 'baseball', 'apparel', 20, 'Great looking and well made baseball pants.', 'M', 'Blue'),
('Baseball Pants', 'baseball', 'apparel', 20, 'Great looking and well made baseball pants.', 'M', 'Black'),
('Baseball Pants', 'baseball', 'apparel', 20, 'Great looking and well made baseball pants.', 'M', 'White'),
('Baseball Pants', 'baseball', 'apparel', 20, 'Great looking and well made baseball pants.', 'M', 'Pink'),
('Baseball Pants', 'baseball', 'apparel', 20, 'Great looking and well made baseball pants.', 'S', 'Red'),
('Baseball Pants', 'baseball', 'apparel', 20, 'Great looking and well made baseball pants.', 'S', 'Blue'),
('Baseball Pants', 'baseball', 'apparel', 20, 'Great looking and well made baseball pants.', 'S', 'Black'),
('Baseball Pants', 'baseball', 'apparel', 20, 'Great looking and well made baseball pants.', 'S', 'White'),
('Baseball Pants', 'baseball', 'apparel', 20, 'Great looking and well made baseball pants.', 'S', 'Pink'),
('Baseball Cleats', 'baseball', 'apparel', 30, 'Great looking and well made baseball cleats.', 'L', 'Black'),
('Baseball Cleats', 'baseball', 'apparel', 30, 'Great looking and well made baseball cleats.', 'L', 'White'),
('Baseball Cleats', 'baseball', 'apparel', 30, 'Great looking and well made baseball cleats.', 'M', 'Black'),
('Baseball Cleats', 'baseball', 'apparel', 30, 'Great looking and well made baseball cleats.', 'M', 'White'),
('Baseball Cleats', 'baseball', 'apparel', 30, 'Great looking and well made baseball cleats.', 'S', 'Black'),
('Baseball Cleats', 'baseball', 'apparel', 30, 'Great looking and well made baseball cleats.', 'S', 'White'),
('Baseball Socks', 'baseball', 'apparel', 5, 'Great looking and well made baseball socks.', 'L', 'Red'),
('Baseball Socks', 'baseball', 'apparel', 5, 'Great looking and well made baseball socks.', 'L', 'Blue'),
('Baseball Socks', 'baseball', 'apparel', 5, 'Great looking and well made baseball socks.', 'L', 'Black'),
('Baseball Socks', 'baseball', 'apparel', 5, 'Great looking and well made baseball socks.', 'L', 'White'),
('Baseball Socks', 'baseball', 'apparel', 5, 'Great looking and well made baseball socks.', 'L', 'Pink'),
('Baseball Socks', 'baseball', 'apparel', 5, 'Great looking and well made baseball socks.', 'M', 'Red'),
('Baseball Socks', 'baseball', 'apparel', 5, 'Great looking and well made baseball socks.', 'M', 'Blue'),
('Baseball Socks', 'baseball', 'apparel', 5, 'Great looking and well made baseball socks.', 'M', 'Black'),
('Baseball Socks', 'baseball', 'apparel', 5, 'Great looking and well made baseball socks.', 'M', 'White'),
('Baseball Socks', 'baseball', 'apparel', 5, 'Great looking and well made baseball socks.', 'M', 'Pink'),
('Baseball Socks', 'baseball', 'apparel', 5, 'Great looking and well made baseball socks.', 'S', 'Red'),
('Baseball Socks', 'baseball', 'apparel', 5, 'Great looking and well made baseball socks.', 'S', 'Blue'),
('Baseball Socks', 'baseball', 'apparel', 5, 'Great looking and well made baseball socks.', 'S', 'Black'),
('Baseball Socks', 'baseball', 'apparel', 5, 'Great looking and well made baseball socks.', 'S', 'White'),
('Baseball Socks', 'baseball', 'apparel', 5, 'Great looking and well made baseball socks.', 'S', 'Pink'),
('Soccer Ball', 'soccer', 'equipment', 20, 'Latest in soccer ball technology.', null, 'Black'),
('Soccer Ball', 'soccer', 'equipment', 20, 'Latest in soccer ball technology.', null, 'Blue'),
('Soccer Ball', 'soccer', 'equipment', 20, 'Latest in soccer ball technology.', null, 'Pink'),
('Shin Guards', 'soccer', 'equipment', 5, 'Protect your shins!', 'L', null),
('Shin Guards', 'soccer', 'equipment', 5, 'Protect your shins!', 'S', null),
('Goalie Gloves', 'soccer', 'equipment', 15, 'Great gloves for your goalie.', 'L', 'Black'),
('Goalie Gloves', 'soccer', 'equipment', 15, 'Great gloves for your goalie.', 'L', 'White'),
('Goalie Gloves', 'soccer', 'equipment', 15, 'Great gloves for your goalie.', 'S', 'Black'),
('Goalie Gloves', 'soccer', 'equipment', 15, 'Great gloves for your goalie.', 'S', 'White'),
('Pop-up Goal', 'soccer', 'equipment', 50, 'Set up your own small game with these pop-up goals', null, null),
('Soccer Cleats', 'soccer', 'apparel', 30, 'Good cleats are essential for any player.', 'L', 'Black'),
('Soccer Cleats', 'soccer', 'apparel', 30, 'Good cleats are essential for any player.', 'L', 'Blue'),
('Soccer Cleats', 'soccer', 'apparel', 30, 'Good cleats are essential for any player.', 'L', 'Red'),
('Soccer Cleats', 'soccer', 'apparel', 30, 'Good cleats are essential for any player.', 'M', 'Black'),
('Soccer Cleats', 'soccer', 'apparel', 30, 'Good cleats are essential for any player.', 'M', 'Blue'),
('Soccer Cleats', 'soccer', 'apparel', 30, 'Good cleats are essential for any player.', 'M', 'Red'),
('Soccer Cleats', 'soccer', 'apparel', 30, 'Good cleats are essential for any player.', 'S', 'Black'),
('Soccer Cleats', 'soccer', 'apparel', 30, 'Good cleats are essential for any player.', 'S', 'Blue'),
('Soccer Cleats', 'soccer', 'apparel', 30, 'Good cleats are essential for any player.', 'S', 'Red'),
('Soccer Jersey', 'soccer', 'apparel', 35, 'Look like the pros playing in this jersey.', 'L', 'Black'),
('Soccer Jersey', 'soccer', 'apparel', 35, 'Look like the pros playing in this jersey.', 'L', 'Blue'),
('Soccer Jersey', 'soccer', 'apparel', 35, 'Look like the pros playing in this jersey.', 'L', 'Red'),
('Soccer Jersey', 'soccer', 'apparel', 35, 'Look like the pros playing in this jersey.', 'L', 'Pink'),
('Soccer Jersey', 'soccer', 'apparel', 35, 'Look like the pros playing in this jersey.', 'L', 'White'),
('Soccer Jersey', 'soccer', 'apparel', 35, 'Look like the pros playing in this jersey.', 'M', 'Black'),
('Soccer Jersey', 'soccer', 'apparel', 35, 'Look like the pros playing in this jersey.', 'M', 'Blue'),
('Soccer Jersey', 'soccer', 'apparel', 35, 'Look like the pros playing in this jersey.', 'M', 'Red'),
('Soccer Jersey', 'soccer', 'apparel', 35, 'Look like the pros playing in this jersey.', 'M', 'Pink'),
('Soccer Jersey', 'soccer', 'apparel', 35, 'Look like the pros playing in this jersey.', 'M', 'White'),
('Soccer Jersey', 'soccer', 'apparel', 35, 'Look like the pros playing in this jersey.', 'S', 'Black'),
('Soccer Jersey', 'soccer', 'apparel', 35, 'Look like the pros playing in this jersey.', 'S', 'Blue'),
('Soccer Jersey', 'soccer', 'apparel', 35, 'Look like the pros playing in this jersey.', 'S', 'Red'),
('Soccer Jersey', 'soccer', 'apparel', 35, 'Look like the pros playing in this jersey.', 'S', 'Pink'),
('Soccer Jersey', 'soccer', 'apparel', 35, 'Look like the pros playing in this jersey.', 'S', 'White'),
('Soccer Shorts', 'soccer', 'apparel', 15, 'Short shorts for playing soccer', 'L', 'Black'),
('Soccer Shorts', 'soccer', 'apparel', 15, 'Short shorts for playing soccer', 'L', 'White'),
('Soccer Shorts', 'soccer', 'apparel', 15, 'Short shorts for playing soccer', 'M', 'Black'),
('Soccer Shorts', 'soccer', 'apparel', 15, 'Short shorts for playing soccer', 'M', 'White'),
('Soccer Shorts', 'soccer', 'apparel', 15, 'Short shorts for playing soccer', 'S', 'Black'),
('Soccer Shorts', 'soccer', 'apparel', 15, 'Short shorts for playing soccer', 'S', 'White'),
('Soccer Socks', 'soccer', 'apparel', 5, 'Long socks to cover your legs while playing socccer', 'L', 'Black'),
('Soccer Socks', 'soccer', 'apparel', 5, 'Long socks to cover your legs while playing socccer', 'L', 'Blue'),
('Soccer Socks', 'soccer', 'apparel', 5, 'Long socks to cover your legs while playing socccer', 'L', 'Red'),
('Soccer Socks', 'soccer', 'apparel', 5, 'Long socks to cover your legs while playing socccer', 'L', 'Pink'),
('Soccer Socks', 'soccer', 'apparel', 5, 'Long socks to cover your legs while playing socccer', 'L', 'White'),
('Soccer Socks', 'soccer', 'apparel', 5, 'Long socks to cover your legs while playing socccer', 'M', 'Black'),
('Soccer Socks', 'soccer', 'apparel', 5, 'Long socks to cover your legs while playing socccer', 'M', 'Blue'),
('Soccer Socks', 'soccer', 'apparel', 5, 'Long socks to cover your legs while playing socccer', 'M', 'Red'),
('Soccer Socks', 'soccer', 'apparel', 5, 'Long socks to cover your legs while playing socccer', 'M', 'Pink'),
('Soccer Socks', 'soccer', 'apparel', 5, 'Long socks to cover your legs while playing socccer', 'M', 'White'),
('Soccer Socks', 'soccer', 'apparel', 5, 'Long socks to cover your legs while playing socccer', 'S', 'Black'),
('Soccer Socks', 'soccer', 'apparel', 5, 'Long socks to cover your legs while playing socccer', 'S', 'Blue'),
('Soccer Socks', 'soccer', 'apparel', 5, 'Long socks to cover your legs while playing socccer', 'S', 'Red'),
('Soccer Socks', 'soccer', 'apparel', 5, 'Long socks to cover your legs while playing socccer', 'S', 'Pink'),
('Soccer Socks', 'soccer', 'apparel', 5, 'Long socks to cover your legs while playing socccer', 'S', 'White'),
('Tennis Ball - Single', 'tennis', 'equipment', 1, 'Loved by dogs and people alike.', null, null),
('Tennis Ball - 3 Pack', 'tennis', 'equipment', 2.50, '3 pack of our best selling tennis balls.', null, null),
('Tennis Racket', 'tennis', 'equipment', 20, 'Great racket for playing tennis.', null, 'Blue'),
('Tennis Racket', 'tennis', 'equipment', 20, 'Great racket for playing tennis.', null, 'Red'),
('Tennis Racket', 'tennis', 'equipment', 20, 'Great racket for playing tennis.', null, 'Pink'),
('Tennis Racket', 'tennis', 'equipment', 20, 'Great racket for playing tennis.', null, 'White'),
('Tennis Net', 'tennis', 'equipment', 150, 'Set up a game in your own backyard.', null, null),
('Basketball', 'basketball', 'equipment', 10, 'Best shooting ball you can buy.', 'L', null),
('Basketball', 'basketball', 'equipment', 10, 'Best shooting ball you can buy.', 'S', null),
('Basketball Hoop', 'basketball', 'equipment', 200, 'Hoop in your driveway!', null, null),
('Basketball Shoes', 'basketball', 'apparel', 50, 'Fasionable and usefull.', 'L', 'Black'),
('Basketball Shoes', 'basketball', 'apparel', 50, 'Fasionable and usefull.', 'L', 'White'),
('Basketball Shoes', 'basketball', 'apparel', 50, 'Fasionable and usefull.', 'L', 'Red'),
('Basketball Shoes', 'basketball', 'apparel', 50, 'Fasionable and usefull.', 'L', 'Blue'),
('Basketball Shoes', 'basketball', 'apparel', 50, 'Fasionable and usefull.', 'M', 'Black'),
('Basketball Shoes', 'basketball', 'apparel', 50, 'Fasionable and usefull.', 'M', 'White'),
('Basketball Shoes', 'basketball', 'apparel', 50, 'Fasionable and usefull.', 'M', 'Red'),
('Basketball Shoes', 'basketball', 'apparel', 50, 'Fasionable and usefull.', 'M', 'Blue'),
('Basketball Shoes', 'basketball', 'apparel', 50, 'Fasionable and usefull.', 'S', 'Black'),
('Basketball Shoes', 'basketball', 'apparel', 50, 'Fasionable and usefull.', 'S', 'White'),
('Basketball Shoes', 'basketball', 'apparel', 50, 'Fasionable and usefull.', 'S', 'Red'),
('Basketball Shoes', 'basketball', 'apparel', 50, 'Fasionable and usefull.', 'S', 'Blue'),
('Basketball Jersey', 'basketball', 'apparel', 20, 'Reversible basketball jersey for your team.', 'L', 'Blue'),
('Basketball Jersey', 'basketball', 'apparel', 20, 'Reversible basketball jersey for your team.', 'L', 'Black'),
('Basketball Jersey', 'basketball', 'apparel', 20, 'Reversible basketball jersey for your team.', 'L', 'White'),
('Basketball Jersey', 'basketball', 'apparel', 20, 'Reversible basketball jersey for your team.', 'L', 'Red'),
('Basketball Jersey', 'basketball', 'apparel', 20, 'Reversible basketball jersey for your team.', 'L', 'Pink'),
('Basketball Jersey', 'basketball', 'apparel', 20, 'Reversible basketball jersey for your team.', 'M', 'Blue'),
('Basketball Jersey', 'basketball', 'apparel', 20, 'Reversible basketball jersey for your team.', 'M', 'Black'),
('Basketball Jersey', 'basketball', 'apparel', 20, 'Reversible basketball jersey for your team.', 'M', 'White'),
('Basketball Jersey', 'basketball', 'apparel', 20, 'Reversible basketball jersey for your team.', 'M', 'Red'),
('Basketball Jersey', 'basketball', 'apparel', 20, 'Reversible basketball jersey for your team.', 'M', 'Pink'),
('Basketball Jersey', 'basketball', 'apparel', 20, 'Reversible basketball jersey for your team.', 'S', 'Blue'),
('Basketball Jersey', 'basketball', 'apparel', 20, 'Reversible basketball jersey for your team.', 'S', 'Black'),
('Basketball Jersey', 'basketball', 'apparel', 20, 'Reversible basketball jersey for your team.', 'S', 'White'),
('Basketball Jersey', 'basketball', 'apparel', 20, 'Reversible basketball jersey for your team.', 'S', 'Red'),
('Basketball Jersey', 'basketball', 'apparel', 20, 'Reversible basketball jersey for your team.', 'S', 'Pink'),
('Basketball Shorts', 'basketball', 'apparel', 15, 'Long shorts to help you look cool on the court', 'L', 'Black'),
('Basketball Shorts', 'basketball', 'apparel', 15, 'Long shorts to help you look cool on the court', 'L', 'White'),
('Basketball Shorts', 'basketball', 'apparel', 15, 'Long shorts to help you look cool on the court', 'L', 'Blue'),
('Basketball Shorts', 'basketball', 'apparel', 15, 'Long shorts to help you look cool on the court', 'M', 'Black'),
('Basketball Shorts', 'basketball', 'apparel', 15, 'Long shorts to help you look cool on the court', 'M', 'White'),
('Basketball Shorts', 'basketball', 'apparel', 15, 'Long shorts to help you look cool on the court', 'M', 'Blue'),
('Basketball Shorts', 'basketball', 'apparel', 15, 'Long shorts to help you look cool on the court', 'S', 'Black'),
('Basketball Shorts', 'basketball', 'apparel', 15, 'Long shorts to help you look cool on the court', 'S', 'White'),
('Basketball Shorts', 'basketball', 'apparel', 15, 'Long shorts to help you look cool on the court', 'S', 'Blue'),
('Football', 'football', 'equipment', 10, 'Great for throwing on Thanksgiving.', null, null),
('Football Pads', 'football', 'equipment', 80, 'Full padding for your body.', 'L', null),
('Football Pads', 'football', 'equipment', 80, 'Full padding for your body.', 'S', null),
('Football Helmet', 'football', 'equipment', 50, 'Protect your head.', 'L', null),
('Football Helmet', 'football', 'equipment', 50, 'Protect your head.', 'S', null),
('Football Cleats', 'football', 'apparel', 30, 'Cleats with great traction.', 'L', 'Black'),
('Football Cleats', 'football', 'apparel', 30, 'Cleats with great traction.', 'L', 'White'),
('Football Cleats', 'football', 'apparel', 30, 'Cleats with great traction.', 'L', 'Pink'),
('Football Cleats', 'football', 'apparel', 30, 'Cleats with great traction.', 'M', 'Black'),
('Football Cleats', 'football', 'apparel', 30, 'Cleats with great traction.', 'M', 'White'),
('Football Cleats', 'football', 'apparel', 30, 'Cleats with great traction.', 'M', 'Pink'),
('Football Cleats', 'football', 'apparel', 30, 'Cleats with great traction.', 'S', 'Black'),
('Football Cleats', 'football', 'apparel', 30, 'Cleats with great traction.', 'S', 'White'),
('Football Cleats', 'football', 'apparel', 30, 'Cleats with great traction.', 'S', 'Pink'),
('Football Jersey', 'football', 'apparel', 25, 'Large jersey that fits over your pads', 'L', 'Pink'),
('Football Jersey', 'football', 'apparel', 25, 'Large jersey that fits over your pads', 'L', 'Black'),
('Football Jersey', 'football', 'apparel', 25, 'Large jersey that fits over your pads', 'L', 'White'),
('Football Jersey', 'football', 'apparel', 25, 'Large jersey that fits over your pads', 'L', 'Blue'),
('Football Jersey', 'football', 'apparel', 25, 'Large jersey that fits over your pads', 'L', 'Red'),
('Football Jersey', 'football', 'apparel', 25, 'Large jersey that fits over your pads', 'M', 'Pink'),
('Football Jersey', 'football', 'apparel', 25, 'Large jersey that fits over your pads', 'M', 'Black'),
('Football Jersey', 'football', 'apparel', 25, 'Large jersey that fits over your pads', 'M', 'White'),
('Football Jersey', 'football', 'apparel', 25, 'Large jersey that fits over your pads', 'M', 'Blue'),
('Football Jersey', 'football', 'apparel', 25, 'Large jersey that fits over your pads', 'M', 'Red'),
('Football Jersey', 'football', 'apparel', 25, 'Large jersey that fits over your pads', 'S', 'Pink'),
('Football Jersey', 'football', 'apparel', 25, 'Large jersey that fits over your pads', 'S', 'Black'),
('Football Jersey', 'football', 'apparel', 25, 'Large jersey that fits over your pads', 'S', 'White'),
('Football Jersey', 'football', 'apparel', 25, 'Large jersey that fits over your pads', 'S', 'Blue'),
('Football Jersey', 'football', 'apparel', 25, 'Large jersey that fits over your pads', 'S', 'Red'),
('Football Pants', 'football', 'apparel', 25, 'Pants with a little extra padding', 'L', 'Red'),
('Football Pants', 'football', 'apparel', 25, 'Pants with a little extra padding', 'L', 'White'),
('Football Pants', 'football', 'apparel', 25, 'Pants with a little extra padding', 'L', 'Black'),
('Football Pants', 'football', 'apparel', 25, 'Pants with a little extra padding', 'M', 'Red'),
('Football Pants', 'football', 'apparel', 25, 'Pants with a little extra padding', 'M', 'White'),
('Football Pants', 'football', 'apparel', 25, 'Pants with a little extra padding', 'M', 'Black'),
('Football Pants', 'football', 'apparel', 25, 'Pants with a little extra padding', 'S', 'Red'),
('Football Pants', 'football', 'apparel', 25, 'Pants with a little extra padding', 'S', 'White'),
('Football Pants', 'football', 'apparel', 25, 'Pants with a little extra padding', 'S', 'Black'),
('Running Shoes', 'running', 'apparel', 40, 'Very sleek, lightweight shoes.', 'L', 'Black'),
('Running Shoes', 'running', 'apparel', 40, 'Very sleek, lightweight shoes.', 'L', 'White'),
('Running Shoes', 'running', 'apparel', 40, 'Very sleek, lightweight shoes.', 'L', 'Red'),
('Running Shoes', 'running', 'apparel', 40, 'Very sleek, lightweight shoes.', 'L', 'Blue'),
('Running Shoes', 'running', 'apparel', 40, 'Very sleek, lightweight shoes.', 'M', 'Black'),
('Running Shoes', 'running', 'apparel', 40, 'Very sleek, lightweight shoes.', 'M', 'White'),
('Running Shoes', 'running', 'apparel', 40, 'Very sleek, lightweight shoes.', 'M', 'Red'),
('Running Shoes', 'running', 'apparel', 40, 'Very sleek, lightweight shoes.', 'M', 'Blue'),
('Running Shoes', 'running', 'apparel', 40, 'Very sleek, lightweight shoes.', 'S', 'Black'),
('Running Shoes', 'running', 'apparel', 40, 'Very sleek, lightweight shoes.', 'S', 'White'),
('Running Shoes', 'running', 'apparel', 40, 'Very sleek, lightweight shoes.', 'S', 'Red'),
('Running Shoes', 'running', 'apparel', 40, 'Very sleek, lightweight shoes.', 'S', 'Blue'),
('Running Shorts', 'running', 'apparel', 10, 'Very short shorts.', 'L', 'Black'),
('Running Shorts', 'running', 'apparel', 10, 'Very short shorts.', 'L', 'Red'),
('Running Shorts', 'running', 'apparel', 10, 'Very short shorts.', 'L', 'Blue'),
('Running Shorts', 'running', 'apparel', 10, 'Very short shorts.', 'M', 'Black'),
('Running Shorts', 'running', 'apparel', 10, 'Very short shorts.', 'M', 'Red'),
('Running Shorts', 'running', 'apparel', 10, 'Very short shorts.', 'M', 'Blue'),
('Running Shorts', 'running', 'apparel', 10, 'Very short shorts.', 'S', 'Black'),
('Running Shorts', 'running', 'apparel', 10, 'Very short shorts.', 'S', 'Red'),
('Running Shorts', 'running', 'apparel', 10, 'Very short shorts.', 'S', 'Blue'),
('Lacross Ball', 'lacross', 'equipment', 3, 'Hard slick ball for lacross.', null, null),
('Lacross Stick', 'lacross', 'equipment', 16, 'Stick with a net on the end.', null, null),
('Lacross Pads', 'lacross', 'equipment', 55, 'Full pads for playing lacross.', 'L', null),
('Lacross Pads', 'lacross', 'equipment', 55, 'Full pads for playing lacross.', 'S', null),
('Lacross Net', 'lacross', 'equipment', 123, 'Comes with 2 nets to set up a game.', null, null),
('Lacross Jersey', 'lacross', 'apparel', 20, 'Lacross jeresy designed to fit over pads', 'L', 'Red'),
('Lacross Jersey', 'lacross', 'apparel', 20, 'Lacross jeresy designed to fit over pads', 'L', 'Blue'),
('Lacross Jersey', 'lacross', 'apparel', 20, 'Lacross jeresy designed to fit over pads', 'L', 'Pink'),
('Lacross Jersey', 'lacross', 'apparel', 20, 'Lacross jeresy designed to fit over pads', 'L', 'White'),
('Lacross Jersey', 'lacross', 'apparel', 20, 'Lacross jeresy designed to fit over pads', 'M', 'Red'),
('Lacross Jersey', 'lacross', 'apparel', 20, 'Lacross jeresy designed to fit over pads', 'M', 'Blue'),
('Lacross Jersey', 'lacross', 'apparel', 20, 'Lacross jeresy designed to fit over pads', 'M', 'Pink'),
('Lacross Jersey', 'lacross', 'apparel', 20, 'Lacross jeresy designed to fit over pads', 'M', 'White'),
('Lacross Jersey', 'lacross', 'apparel', 20, 'Lacross jeresy designed to fit over pads', 'S', 'Red'),
('Lacross Jersey', 'lacross', 'apparel', 20, 'Lacross jeresy designed to fit over pads', 'S', 'Blue'),
('Lacross Jersey', 'lacross', 'apparel', 20, 'Lacross jeresy designed to fit over pads', 'S', 'Pink'),
('Lacross Jersey', 'lacross', 'apparel', 20, 'Lacross jeresy designed to fit over pads', 'S', 'White'),
('Hockey Puck', 'hockey', 'equipment', 5, 'Small puck for playing ice hockey.', null, null),
('Hockey Stick', 'hockey', 'equipment', 20, 'Curved stick for playing ice hockey.', null, null),
('Hockey Pads', 'hockey', 'equipment', 90, 'Full set of hockey pads.', 'L', null),
('Hockey Pads', 'hockey', 'equipment', 90, 'Full set of hockey pads.', 'M', null),
('Hockey Pads', 'hockey', 'equipment', 90, 'Full set of hockey pads.', 'S', null),
('Hockey Net', 'hockey', 'equipment', 160, 'Comes with two nets to set up a game.', null, null),
('Hockey Sweater', 'hockey', 'apparel', 30, 'Hockey jeresy designed to fit over pads', 'L', 'Red'),
('Hockey Sweater', 'hockey', 'apparel', 30, 'Hockey jeresy designed to fit over pads', 'L', 'Blue'),
('Hockey Sweater', 'hockey', 'apparel', 30, 'Hockey jeresy designed to fit over pads', 'L', 'Black'),
('Hockey Sweater', 'hockey', 'apparel', 30, 'Hockey jeresy designed to fit over pads', 'L', 'White'),
('Hockey Sweater', 'hockey', 'apparel', 30, 'Hockey jeresy designed to fit over pads', 'L', 'Pink'),
('Hockey Sweater', 'hockey', 'apparel', 30, 'Hockey jeresy designed to fit over pads', 'M', 'Red'),
('Hockey Sweater', 'hockey', 'apparel', 30, 'Hockey jeresy designed to fit over pads', 'M', 'Blue'),
('Hockey Sweater', 'hockey', 'apparel', 30, 'Hockey jeresy designed to fit over pads', 'M', 'Black'),
('Hockey Sweater', 'hockey', 'apparel', 30, 'Hockey jeresy designed to fit over pads', 'M', 'White'),
('Hockey Sweater', 'hockey', 'apparel', 30, 'Hockey jeresy designed to fit over pads', 'M', 'Pink'),
('Hockey Sweater', 'hockey', 'apparel', 30, 'Hockey jeresy designed to fit over pads', 'S', 'Red'),
('Hockey Sweater', 'hockey', 'apparel', 30, 'Hockey jeresy designed to fit over pads', 'S', 'Blue'),
('Hockey Sweater', 'hockey', 'apparel', 30, 'Hockey jeresy designed to fit over pads', 'S', 'Black'),
('Hockey Sweater', 'hockey', 'apparel', 30, 'Hockey jeresy designed to fit over pads', 'S', 'White'),
('Hockey Sweater', 'hockey', 'apparel', 30, 'Hockey jeresy designed to fit over pads', 'S', 'Pink'),
('Water Bottle', 'gear', 'accessory', 8, 'Holds water so you can stay hydrated.', null, 'Black'),
('Head Band', 'gear', 'accessory', 5, 'Keeps the sweat out of your face', null, 'Black'),
('Head Band', 'gear', 'accessory', 5, 'Keeps the sweat out of your face', null, 'White'),
('Head Band', 'gear', 'accessory', 5, 'Keeps the sweat out of your face', null, 'Red'),
('Head Band', 'gear', 'accessory', 5, 'Keeps the sweat out of your face', null, 'Blue'),
('Athletic Tape', 'gear', 'accessory', 5, 'Roll of strong athletic tape.', null, 'White'),
('Athletic Tape', 'gear', 'accessory', 5, 'Roll of strong athletic tape.', null, 'Black'),
('Water Cooler', 'gear', 'accessory', 25, 'Holds 5 gallons of liquid.', null, null),
('Ice Pack', 'gear', 'accessory', 12, 'For icing your injuries.', null, null),
('Fishing Pole', 'fishing', 'equipment', 45, 'Pole for catching fish.', null, null),
('Fishing Line', 'fishing', 'equipment', 5, 'Roll of fishing line, 100ft.', null, null),
('Fake Worm', 'fishing', 'equipment', 3, 'Bait for fishing.', null, null),
('Fake Minnow', 'fishing', 'equipment', 5, 'Bait for catching bigger fish.', null, null),
('Fishing Hat', 'fishing', 'apparel', 25, 'Bucket hat to keep the sun off', null, 'Blue'),
('Fishing Hat', 'fishing', 'apparel', 25, 'Bucket hat to keep the sun off', null, 'Black'),
('Fishing Hat', 'fishing', 'apparel', 25, 'Bucket hat to keep the sun off', null, 'White'),
('Fishing Shirt', 'fishing', 'apparel', 35, 'Long sleeve but breathable', 'L', 'Black'),
('Fishing Shirt', 'fishing', 'apparel', 35, 'Long sleeve but breathable', 'L', 'White'),
('Fishing Shirt', 'fishing', 'apparel', 35, 'Long sleeve but breathable', 'L', 'Blue'),
('Fishing Shirt', 'fishing', 'apparel', 35, 'Long sleeve but breathable', 'M', 'Black'),
('Fishing Shirt', 'fishing', 'apparel', 35, 'Long sleeve but breathable', 'M', 'White'),
('Fishing Shirt', 'fishing', 'apparel', 35, 'Long sleeve but breathable', 'M', 'Blue'),
('Fishing Shirt', 'fishing', 'apparel', 35, 'Long sleeve but breathable', 'S', 'Black'),
('Fishing Shirt', 'fishing', 'apparel', 35, 'Long sleeve but breathable', 'S', 'White'),
('Fishing Shirt', 'fishing', 'apparel', 35, 'Long sleeve but breathable', 'S', 'Blue');

